feat: add map generator and display
pollubnet/fracture pull request #73
Opened 2024-06-09 22:00 UTC by ktos

2024-06-16 14:09 UTC, purifetchi requested changes
some initial style issues, the code seems fine otherwise

the `var` comment applies to most of the files too, but i didn't want to spam every single file with the same comment

2024-06-16 14:09 UTC, purifetchi commented on Server/Modules/MapGenerator/Services/MapGeneratorService.cs
> +    //private Dictionary<(TemperatureType, HeightType), Biome> biomesDictionary = new Dictionary<(TemperatureType, HeightType), Biome>
unless this code is to be used later, i don't think we should keep commented out code

2024-06-16 14:09 UTC, purifetchi commented on Server/Modules/MapGenerator/Services/MapGeneratorService.cs
> +        Node[,] grid = new Node[width, height];
`var` please

2024-06-16 14:09 UTC, purifetchi commented on Server/Modules/NoiseGenerator/Services/Perlin.cs
> +﻿namespace Fracture.Server.Modules.NoiseGenerator.Services;
to be fair i think we should sooner or later replace our hand-rolled implementation of the perlin noise generator with a NuGet package

2024-06-16 14:09 UTC, purifetchi commented on Server/Modules/MapGenerator/Services/MapGeneratorService.cs
> +                if (heightMap[x, y] < 0.02f)
i... don't really like this, although i can't come up with a better solution off the top of my head for now.

(i assume this is for biomes?)

2024-06-17 19:58 UTC, purifetchi commented
`Program.cs` is conflicting

2024-06-18 09:40 UTC, ktos commented
Rebased.

2024-06-18 09:45 UTC, purifetchi approved these changes

2024-06-18 09:45 UTC, merged